apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-nfs-pod 
  labels:
    name: nginx-nfs-pod
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-nfs-pod
          image: gcr.io/delta-carving-312819/nginx:latest 
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nfsvol 
              mountPath: /usr/share/nginx/html 
      securityContext:
          supplementalGroups: [100003] 
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-pvc 
